name: update agent versions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  agent-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: update agent versions
        run: |
          ./.github/scripts/check-claude-update.sh
          ./.github/scripts/check-codex-update.sh
          ./.github/scripts/check-gemini-update.sh

      - name: create pr
        uses: peter-evans/create-pull-request@v8
        with:
          sign-commits: true
          commit-message: "chore: bump agent versions"
          title: "chore: bump agent versions"
          body: |
            automated update of agent versions.
          branch: chore/bump-agent-versions
