name: update claude version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  claude-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: update claude version
        run: |
          ./.github/scripts/check-claude-update.sh

      - name: create pr
        uses: peter-evans/create-pull-request@v8
        with:
          sign-commits: true
          commit-message: "chore: bump claude version"
          title: "chore: bump claude version"
          body: |
            automated update of claude version.
          branch: chore/claude-version-bump
          delete-branch: true